function execute() {
    return Response.success([
        {title: "Action", input: "/the-loai/action", script: "gen.js"},
        {title: "Adventure", input: "/the-loai/adventure", script: "gen.js"},
        {title: "Anime", input: "/the-loai/anime", script: "gen.js"},
        {title: "Chuyển Sinh", input: "/the-loai/chuyen-sinh", script: "gen.js"},
        {title: "Cổ Đại", input: "/the-loai/co-dai", script: "gen.js"},
        {title: "Comedy", input: "/the-loai/comedy", script: "gen.js"},
        {title: "Comic", input: "/the-loai/comic", script: "gen.js"},
        {title: "Cooking", input: "/the-loai/cooking", script: "gen.js"},
        {title: "Doujinshi", input: "/the-loai/doujinshi", script: "gen.js"},
        {title: "Drama", input: "/the-loai/drama", script: "gen.js"},
        {title: "Ecchi", input: "/the-loai/ecchi", script: "gen.js"},
        {title: "Fantasy", input: "/the-loai/fantasy", script: "gen.js"},
        {title: "Harem", input: "/the-loai/harem", script: "gen.js"},
        {title: "Historical", input: "/the-loai/historical", script: "gen.js"},
        {title: "Horror", input: "/the-loai/horror", script: "gen.js"},
        {title: "Josei", input: "/the-loai/josei", script: "gen.js"},
        {title: "Live action", input: "/the-loai/live-action", script: "gen.js"},
        {title: "Manga", input: "/the-loai/manga", script: "gen.js"},
        {title: "Manhua", input: "/the-loai/manhua", script: "gen.js"},
        {title: "Manhwa", input: "/the-loai/manhwa", script: "gen.js"},
        {title: "Martial Arts", input: "/the-loai/martial-arts", script: "gen.js"},
        {title: "Mature", input: "/the-loai/mature", script: "gen.js"},
        {title: "Mecha", input: "/the-loai/mecha", script: "gen.js"},
        {title: "Mystery", input: "/the-loai/mystery", script: "gen.js"},
        {title: "Ngôn Tình", input: "/the-loai/ngon-tinh", script: "gen.js"},
        {title: "One shot", input: "/the-loai/one-shot", script: "gen.js"},
        {title: "Psychological", input: "/the-loai/psychological", script: "gen.js"},
        {title: "Romance", input: "/the-loai/romance", script: "gen.js"},
        {title: "School Life", input: "/the-loai/school-life", script: "gen.js"},
        {title: "Sci-fi", input: "/the-loai/sci-fi", script: "gen.js"},
        {title: "Seinen", input: "/the-loai/seinen", script: "gen.js"},
        {title: "Shoujo", input: "/the-loai/shoujo", script: "gen.js"},
        {title: "Shounen", input: "/the-loai/shounen", script: "gen.js"},
        {title: "Slice of Life", input: "/the-loai/slice-of-life", script: "gen.js"},
        {title: "Smut", input: "/the-loai/smut", script: "gen.js"},
        {title: "Sports", input: "/the-loai/sports", script: "gen.js"},
        {title: "Supernatural", input: "/the-loai/supernatural", script: "gen.js"},
        {title: "Tạp chí truyện tranh", input: "/the-loai/tap-chi-truyen-tranh", script: "gen.js"},
        {title: "Tragedy", input: "/the-loai/tragedy", script: "gen.js"},
        {title: "Trinh Thám", input: "/the-loai/trinh-tham", script: "gen.js"},
        {title: "Truyện Màu", input: "/the-loai/truyen-mau", script: "gen.js"},
        {title: "Truyện scan", input: "/the-loai/truyen-scan", script: "gen.js"},
        {title: "Webtoon", input: "/the-loai/webtoon", script: "gen.js"},
        {title: "Xuyên Không", input: "/the-loai/xuyen-khong", script: "gen.js"}
    ]);
}
