load("config.js");

function execute() {
    return Response.success([
        { title: "Manhwa 18+", input: "/genres/manhwa", script: "gen.js" },
        { title: "Hentai Không Che", input: "/genres/hentai-khong-che", script: "gen.js" },
        { title: "3D Hentai", input: "/genres/3d-hentai", script: "gen.js" },
        { title: "Full Color", input: "/genres/full-color", script: "gen.js" },
        { title: "Oneshot", input: "/genres/oneshot", script: "gen.js" },
        { title: "NTR", input: "/genres/ntr", script: "gen.js" },
        { title: "Milf", input: "/genres/milf", script: "gen.js" },
        { title: "Incest", input: "/genres/incest", script: "gen.js" },
        { title: "Ahegao", input: "/genres/ahegao", script: "gen.js" },
        { title: "Anal", input: "/genres/anal", script: "gen.js" },
        { title: "BBW", input: "/genres/bbw", script: "gen.js" },
        { title: "BDSM", input: "/genres/bdsm", script: "gen.js" },
        { title: "Cheating", input: "/genres/cheating", script: "gen.js" },
        { title: "Cosplay", input: "/genres/cosplay", script: "gen.js" },
        { title: "Dark Skin", input: "/genres/dark-skin", script: "gen.js" },
        { title: "Doujinshi", input: "/genres/doujinshi", script: "gen.js" },
        { title: "Ecchi", input: "/genres/ecchi", script: "gen.js" },
        { title: "Femdom", input: "/genres/femdom", script: "gen.js" },
        { title: "Futanari", input: "/genres/futanari", script: "gen.js" },
        { title: "Gangbang", input: "/genres/gangbang", script: "gen.js" },
        { title: "Gyaru", input: "/genres/gyaru", script: "gen.js" },
        { title: "Harem", input: "/genres/harem", script: "gen.js" },
        { title: "Humiliation", input: "/genres/humiliation", script: "gen.js" },
        { title: "Idol", input: "/genres/idol", script: "gen.js" },
        { title: "Isekai", input: "/genres/isekai", script: "gen.js" },
        { title: "Kemonomimi", input: "/genres/kemonomimi", script: "gen.js" },
        { title: "Masturbation", input: "/genres/masturbation", script: "gen.js" },
        { title: "Mind Break", input: "/genres/mind-break", script: "gen.js" },
        { title: "Mind Control", input: "/genres/mind-control", script: "gen.js" },
        { title: "Monster Girl", input: "/genres/monster-girl", script: "gen.js" },
        { title: "Netorare", input: "/genres/netorare", script: "gen.js" },
        { title: "Oral", input: "/genres/oral", script: "gen.js" },
        { title: "Paizuri", input: "/genres/paizuri", script: "gen.js" },
        { title: "Romance", input: "/genres/romance", script: "gen.js" },
        { title: "Schoolgirl", input: "/genres/schoolgirl", script: "gen.js" },
        { title: "Shota", input: "/genres/shota", script: "gen.js" },
        { title: "Tentacles", input: "/genres/tentacles", script: "gen.js" },
        { title: "Tsundere", input: "/genres/tsundere", script: "gen.js" },
        { title: "Vanilla", input: "/genres/vanilla", script: "gen.js" },
        { title: "Virgin", input: "/genres/virgin", script: "gen.js" },
        { title: "Yaoi", input: "/genres/yaoi", script: "gen.js" },
        { title: "Yuri", input: "/genres/yuri", script: "gen.js" }
    ]);
}
